# Generated by Django 2.0.2 on 2018-02-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('1', 'Illustrations'), ('2', 'Interior'), ('3', 'Random'), ('4', 'Siberian'), ('5', 'Wakanda')], max_length=1),
        ),
    ]
