# Generated by Django 2.0.2 on 2018-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20180226_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('1', 'Poka Universe'), ('2', 'Singapore'), ('3', 'Nairobi, Kenya'), ('4', 'Siberia'), ('5', 'Wakanda')], max_length=1),
        ),
    ]
